### ISSUE TITLE
PHP errors for non-string context values

### ISSUE THREAD

**Issue by chrisminett** [bzikarsky/gelf-php#50] opened 2015-10-19 13:54 UTC
When the `log()` `$context` array contains non-string values (such as other arrays), a PHP Notice and PHP Warning are generated as the values are treated as if they will always be strings.

[PSR-3 §1.3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#13-context) states that the context array can contain anything, and the implementation "MUST NOT (...) raise any php error, warning or notice".

It seems that the notice arises from the `interpolate()` method which is a copy of the FIG example code (shame!) and the warning from a specific implementation in `Message::toArray()` which filters out non-strings.

If a non-string is encountered it would be good to modify it, such as running arrays through `json_encode()`

**Comment by chrisminett** [comment] 2015-10-19 14:00
Example, tested on v1.4.0:

```php
$logger = new \Gelf\Logger();
$logger->error('Example error', [
    'ctxt1' => 'string',
    'ctxt2' => [
        'sub1' => 'val1',
        'sub2' => 'val2'
    ]
]);
```

Error log:
```
PHP Notice:  Array to string conversion in vendor/graylog2/gelf-php/src/Gelf/Logger.php on line 189
PHP Warning:  strlen() expects parameter 1 to be string, array given in vendor/graylog2/gelf-php/src/Gelf/Message.php on line 300
```

**Comment by bzikarsky** [comment] 2015-10-19 16:05
Confirmed, I'll look into fixing (and testing) this in the next version. I'll also happily accept any PR, if you have time/are interested in this issue. :)

**Comment by bzikarsky** [comment] 2015-10-21 07:50
While we are at it: It's pretty much a duplicate of https://github.com/bzikarsky/gelf-php/pull/38/files.

**Closed** 2015-10-21 08:06 UTC
Labels: duplicate
